"""0004_hired_payment_cols — x402 payment metadata on hired_agents.

FU-2 (design id 52, decision Q5) extends HiredAgent with the 5 nullable
payment columns + the `(address, status)` index:

    amount           NUMERIC(38,18)  $U units (18 decimals)
    token            TEXT            token address (checksummed)
    rail             TEXT            "eip3009" in v1 (TEXT for future rails)
    pay_to           TEXT            agent_wallet echo (recipient-bound)
    challenge_expiry TIMESTAMPTZ     created_at + maxTimeoutSeconds

All columns are nullable, so no data migration is required. The index backs
the lazy TTL sweep (`WHERE address = :u AND status = 'pending' AND
challenge_expiry < now()`) and per-user hire lists.

Generated by hand to mirror the SQLAlchemy model exactly (autogenerate
needs a live Postgres; the `alembic check` gate runs in CI/compose).
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "0004_hired_payment_cols"
down_revision: Union[str, None] = "0003_health_status_jsonb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("hired_agents", sa.Column("amount", sa.Numeric(38, 18), nullable=True))
    op.add_column("hired_agents", sa.Column("token", sa.Text(), nullable=True))
    op.add_column("hired_agents", sa.Column("rail", sa.Text(), nullable=True))
    op.add_column("hired_agents", sa.Column("pay_to", sa.Text(), nullable=True))
    op.add_column(
        "hired_agents",
        sa.Column("challenge_expiry", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(
        "ix_hired_agents_address_status",
        "hired_agents",
        ["address", "status"],
    )


def downgrade() -> None:
    op.drop_index("ix_hired_agents_address_status", table_name="hired_agents")
    op.drop_column("hired_agents", "challenge_expiry")
    op.drop_column("hired_agents", "pay_to")
    op.drop_column("hired_agents", "rail")
    op.drop_column("hired_agents", "token")
    op.drop_column("hired_agents", "amount")
